name: '.NET - On push'

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'dotnet/**'
      - '.github/workflows/dotnet-*.yml'
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/dotnet-build-and-test.yml
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
