name: 'Rust - On pull request'

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'rust/**'
      - '.github/workflows/rust-*.yml'

jobs:
  build-and-test:
    uses: ./.github/workflows/rust-build-and-test.yml
